<?php namespace ProcessWire;

return [
    'admission' => [
        'label' => 'Admission',
        'file' => 'components/module-admission.php',
        'anchor' => 'module-1',
        'default_sort_order' => 1,
        'default_enabled' => 1,
        'default_mandatory' => 1,
        'fields' => [
            'patient_name' => 'Patient Name',
            'phone' => 'Phone',
            'phone_secondary' => 'Secondary Phone',
            'guardian' => 'Guardian',
            'address' => 'Address',
            'gender' => 'Gender',
            'patient_age' => 'Patient Age',
            'age_unit' => 'Age Unit',
            'room_bed' => 'Bed / Room',
            'admission_date' => 'Admission Date',
            'discharge_date' => 'Discharge Date',
        ],
        'actions' => [
            'save_admission' => 'Save Admission',
        ],
    ],
    'diagnosis' => [
        'label' => 'Diagnosis',
        'file' => 'components/module-diagnosis.php',
        'anchor' => 'module-2',
        'default_sort_order' => 2,
        'default_enabled' => 1,
        'default_mandatory' => 1,
        'fields' => [
            'primary_diagnosis_text' => 'Primary Diagnosis',
        ],
        'actions' => [
            'save_diagnosis' => 'Save Diagnosis',
        ],
    ],
    'history' => [
        'label' => 'History',
        'file' => 'components/module-history.php',
        'anchor' => 'module-3',
        'default_sort_order' => 3,
        'default_enabled' => 1,
        'default_mandatory' => 0,
        'fields' => [
            'chief_complaint' => 'Chief Complaint',
            'history_present_illness' => 'History of Present Illness',
            'past_medical_history' => 'Past Medical History',
            'past_surgical_history' => 'Past Surgical History',
            'comorbidity_none' => 'Comorbidity None',
            'comorbidity_flags' => 'Comorbidity Flags',
            'comorb_custom_condition' => 'Custom Comorbidity',
            'comorb_drug_condition' => 'Comorbidity Drug Condition',
            'comorb_drug_name' => 'Comorbidity Drug Name',
            'comorb_drug_dose' => 'Comorbidity Drug Dose',
            'drug_hist_name' => 'Drug History Name',
            'drug_hist_dose' => 'Drug History Dose',
            'drug_hist_freq' => 'Drug History Frequency',
        ],
        'actions' => [
            'save_history' => 'Save History',
        ],
    ],
    'examination' => [
        'label' => 'Examination',
        'file' => 'components/module-examination.php',
        'anchor' => 'module-4',
        'default_sort_order' => 4,
        'default_enabled' => 1,
        'default_mandatory' => 0,
        'fields' => [
            'vitals_pulse' => 'Pulse',
            'vitals_bp' => 'Blood Pressure',
            'vitals_temp' => 'Temperature',
            'vitals_spo2' => 'SpO2',
            'inspection' => 'General Findings',
            'examination_findings' => 'Local Findings',
        ],
        'actions' => [
            'save_examination' => 'Save Examination',
        ],
    ],
    'investigations' => [
        'label' => 'Investigations',
        'file' => 'components/module-investigations.php',
        'anchor' => 'module-5',
        'default_sort_order' => 5,
        'default_enabled' => 1,
        'default_mandatory' => 0,
        'fields' => [
            'investigation_date' => 'Investigation Date',
            'investigation_name' => 'Investigation Name',
            'investigation_findings' => 'Investigation Findings',
            'include_in_discharge' => 'Include In Discharge',
        ],
        'actions' => [
            'save_investigations' => 'Save Investigation',
        ],
    ],
    'ot-plan' => [
        'label' => 'OT Plan',
        'file' => 'components/module-surgery-plan.php',
        'anchor' => 'module-6',
        'default_sort_order' => 6,
        'default_enabled' => 1,
        'default_mandatory' => 0,
        'fields' => [
            'proc_name' => 'Procedure Name',
            'proc_date' => 'OT Date',
            'proc_time' => 'OT Time',
            'surgeon_name' => 'Surgeon',
            'proc_side' => 'Procedure Side',
            'anesthesia_type' => 'Anesthesia Type',
            'c_arm_required' => 'C-Arm Required',
            'microscope_required' => 'Microscope Required',
            'implant_details' => 'Implant Details',
            'anesthesiologist_name' => 'Anesthesiologist',
        ],
        'actions' => [
            'save_ot_plan' => 'Save OT Plan',
        ],
    ],
    'preop-print' => [
        'label' => 'Pre-op Print',
        'file' => 'components/module-preop-print.php',
        'anchor' => 'module-7',
        'default_sort_order' => 7,
        'default_enabled' => 1,
        'default_mandatory' => 0,
        'fields' => [],
        'actions' => [
            'generate_preop_pdf' => 'Generate Pre-op PDF',
        ],
    ],
    'operation-note' => [
        'label' => 'Operation Note',
        'file' => 'components/module-operation-note.php',
        'anchor' => 'module-8',
        'default_sort_order' => 8,
        'default_enabled' => 1,
        'default_mandatory' => 0,
        'fields' => [
            'procedure_name' => 'Operation Name',
            'surgery_date' => 'Surgery Date',
            'start_time' => 'Start Time',
            'end_time' => 'End Time',
            'opnote_anesthesia_type' => 'Anesthesia Type',
            'surgeon_name' => 'Surgeon',
            'anesthesiologist_name' => 'Anesthesiologist',
            'assistant_name' => 'Assistant',
            'implants_used' => 'Implants Used',
            'patient_position' => 'Patient Position',
            'incision' => 'Incision',
            'surgical_approach' => 'Operative Description',
            'tourniquet_time' => 'Tourniquet Time',
            'closure_details' => 'Closure',
            'procedure_steps_block' => 'Procedure Steps',
        ],
        'actions' => [
            'save_operation_note' => 'Save Operation Note',
        ],
    ],
    'hospital-course' => [
        'label' => 'Hospital Course',
        'file' => 'components/module-hospital-course.php',
        'anchor' => 'module-9',
        'default_sort_order' => 9,
        'default_enabled' => 1,
        'default_mandatory' => 0,
        'fields' => [
            'course_entry_date' => 'Course Entry Date',
            'course_entry_type' => 'Course Entry Type',
            'course_entry_note' => 'Course Entry Note',
        ],
        'actions' => [
            'save_hospital_course' => 'Save Hospital Course',
        ],
    ],
    'condition' => [
        'label' => 'Condition',
        'file' => 'components/module-condition.php',
        'anchor' => 'module-10',
        'default_sort_order' => 10,
        'default_enabled' => 1,
        'default_mandatory' => 0,
        'fields' => [
            'general_condition' => 'General Condition',
            'pain_scale' => 'Pain Scale',
        ],
        'actions' => [
            'save_condition' => 'Save Condition',
        ],
    ],
    'medications' => [
        'label' => 'Medications',
        'file' => 'components/module-medications.php',
        'anchor' => 'module-10a',
        'default_sort_order' => 11,
        'default_enabled' => 1,
        'default_mandatory' => 0,
        'fields' => [
            'med_drug' => 'Drug',
            'med_dose' => 'Dose',
            'med_frequency' => 'Frequency',
            'med_duration' => 'Duration',
        ],
        'actions' => [
            'save_medications' => 'Save Medications',
        ],
    ],
    'advice' => [
        'label' => 'Advice & Follow-up',
        'file' => 'components/module-advice.php',
        'anchor' => 'module-10b',
        'default_sort_order' => 12,
        'default_enabled' => 1,
        'default_mandatory' => 0,
        'fields' => [
            'follow_up_instructions' => 'Instructions',
            'subsequent_treatment_plan' => 'Subsequent Treatment Plan',
            'review_date' => 'Follow-up Date',
        ],
        'actions' => [
            'save_advice' => 'Save Advice',
        ],
    ],
    'discharge-engine' => [
        'label' => 'Final Output',
        'file' => 'components/module-discharge-engine.php',
        'anchor' => 'module-11',
        'default_sort_order' => 13,
        'default_enabled' => 1,
        'default_mandatory' => 0,
        'fields' => [],
        'actions' => [
            'generate_final_pdf' => 'Generate Final PDF',
            'lock_case' => 'Lock Case',
            'save_draft' => 'Save Draft',
            'preview_mode' => 'Preview Mode',
        ],
    ],
];
